/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Image_Native_ImageGen */

#ifndef _Included_Image_Native_ImageGen
#define _Included_Image_Native_ImageGen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Image_Native_ImageGen
 * Method:    blur
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_Image_Native_ImageGen_blur
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     Image_Native_ImageGen
 * Method:    ColorCut
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_Image_Native_ImageGen_ColorCut
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
